### ISSUE TITLE
关于通过header传递x-auth-token

### ISSUE THREAD

**Issue by feiZhang** [open-node/open-rest-es6-boilerplate#2]
本项目通过 req.headers['x-auth-token'] 获取token
代码：node_modules/open-rest/lib/utils.js
    return req.headers['x-auth-token'] || req.params.access_token || req.params.accessToken;
但是，在跨域访问本项目生成的api，header中包含 x-auth-token 不能通过 restify 的验证
restify中只有：
var ALLOW_HEADERS = [
    'accept',
    'accept-version',
    'content-type',
    'request-id',
    'origin',
    'x-api-version',
    'x-request-id'
];
能通过验证，而且无法通过配置，增加头。

我通过在index.js 中增加。
restify.CORS.ALLOW_HEADERS.push("x-auth-token");
强行增加了header。
请问，有没有其他更优雅的方法？
谢谢。

**Comment by zhaoxiongfei** [comment]
跨域的问题通过设置nginx代理来解决。

**Comment by feiZhang** [comment]
ok..明白，，3x

**Comment by zhaoxiongfei** [comment]
做 web 开发一定要善用 nginx
